/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      animation: {
        'spin-slow': 'spin 5s linear infinite',
        'wiggle': 'wiggle 6s ease-in-out infinite',
        'titleflip': 'titleflip 8s cubic-bezier( 0.14, 0.76, 0.41, 0.98 )',
        'titledotsright': 'titledotsright 8s ease-in-out infinite',
      },
      keyframes: {
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        titleflip: {
          '0%': { transform: 'rotateX(0)' },
          '70%,100%': { transform: 'rotateX(1800deg)'},
        },
        titledotsright: {
          '0%, 100%': { transform: 'translateX(0px)' },
          '50%': { transform: '-translateX(300px)' },
        },
      },
      colors: {
        'cygnus-bg': '#890304',
        'cy-primary-text': '#002263',
        'cy-secondary-bg': '#E1CA6D',
        'cy-light-bg': '#FBF6E0',
        'cy-light-text': '#035B9B',
        'cygnus-black': '#141414',
        'cygnus-white': '#FCFCFC',
      },
      fontFamily: {
        Young : ["Young Serif", "serif"],
        league: ['"League Gothic"', 'sans-serif'],
        serif: ["Source Serif Pro", 'serif'], // Add the font family here
      },
      backgroundImage: {
        'eventtopbordertwo': "url('/images/eventtopbordertwo.png')",
        'top-cutone': "url('/images/topcurtone.png')",
        'curtain-image': "url('/images/royal_curtains.png')",
        'side-curtain': "url('/images/sidecutaine.png')",
        'side-curtain-lft': "url('/images/sideimagetwo.png')",
        'cygnus-btn-bg': "linear-gradient(45deg, #002263 9%, #035B9B 51%, #002263 88%)",
        'authbg': "url('/images/successbg.png')",
        'abouttopborder': "url('/images/abouttopborder.png')",
        'teamtopborder': "url('/images/teamtopborder.png')",
        'sponerstopborder': "url('/images/sponserstopborder.png')",
        'eventtopborder': "url('i/mages/eventtopborder.png')",
        "event-bgcolor": "linear-gradient( rgba(137,3,4,0) 42%, rgba(88,0,1,1) 79%)",
        "highlight-bgcolor": "linear-gradient( rgba(0,0,0,0) 0%, rgba(0,0,0,0.5) 86%)",
        "hover-highlight-bgcolor": "linear-gradient( rgba(0,0,0,0) 0%, rgba(0,0,0,0) 86%)",
        'top-border': "url('/images/bordertopimg.png')",
        'bottom-border-bg' : "url('/images/bottompattern.png')",
        'video-border': "url('/images/videoborder.png')",
        'videobg': "url('/images/videobg.png')",
        'royalbg': "url('/images/royalbg.png')",
        'patterntwo': "url('/images/bgimagethree.png')",
        'royalbgtwo': "url('/images/royalbg2.png')",
        'top-border-repeat' : "url('/borderrepertimage.png')",
        'cygnus-title-card' : "url('/images/cygnustitlecard.png')",
        'dots-gradient' :  "radial-gradient(circle ,#FFD58B 0% , #EEC276 100%)",
        'line-gradient-lr' : "linear-gradient(to right,  #890304 0% , #F8F2BF 100%)",
        'line-gradient-rl' : "linear-gradient(to left,  #890304 0% , #F8F2BF 100%)",
        'titlecardbg' : "url('/images/titlecardbg.png')",
        'profileborder': "url('/images/profileborder.png')",
        'loginbg':"url('/images/loginbg.png')",'eventtopbordertwo': "url('/images/eventtopbordertwo.png')",
        'cygnus-btn-bg': "linear-gradient(45deg, #002263 9%, #035B9B 51%, #002263 88%)",
        'authbg': "url('/images/successbg.png')",
        'abouttopborder': "url('/images/abouttopborder.png')",
        'teamtopborder': "url('/images/teamtopborder.png')",
        'sponerstopborder': "url('/images/sponserstopborder.png')",
        'eventtopborder': "url('/images/eventtopborder.png')",
        "event-bgcolor": "linear-gradient( rgba(137,3,4,0) 42%, rgba(88,0,1,1) 79%)",
        'top-border': "url('/images/bordertopimg.png')",
        'bottom-border-bg' : "url('/images/bottompattern.png')",
        'video-border': "url('/images/videoborder.png')",
        'videobg': "url('/images/videobg.png')",
        'royalbg': "url('/images/royalbg.png')",
        'patterntwo': "url('/images/bgimagethree.png')",
        'royalbgtwo': "url('/images/royalbg2.png')",
        'cygnus-title-card' : "url('/images/cygnustitlecard.png')",
        'dots-gradient' :  "radial-gradient(circle ,#FFD58B 0% , #EEC276 100%)",
        'line-gradient-lr' : "linear-gradient(to right,  #890304 0% , #F8F2BF 100%)",
        'line-gradient-rl' : "linear-gradient(to left,  #890304 0% , #F8F2BF 100%)",
        'titlecardbg' : "url('/images/titlecardbg.png')",
        'profileborder': "url('/images/profileborder.png')",
        'loginbg':"url('/images/loginbg.png')",
        'top-border-repeat': "url('/images/borderrepertimage.png')",
        'sportsbg': "url('/images/sportsbg.png')",
      }
    },
  },
  plugins: [],
}

